sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
  - >-
      openssl aes-256-cbc
      -K $encrypted_xxxxxxxxxxxx_key
      -iv $encrypted_xxxxxxxxxxxx_iv
      -in csif.enc
      -out csif
      -d
  - chmod 600 csif
  - eval $(ssh-agent -s)
  - ssh-add csif
script:
  - pdflatex -interaction=nonstopmode -halt-on-error matalap-megoldasok.tex
deploy:
  provider: releases
  file: "matalap-megoldasok.pdf"
  skip_cleanup: true
  on:
    tags: true
    repo: szenadam/csifz-matalap-megoldasok
